### PR TITLE
Use react-virtualized CellMeasurer

### PR DESCRIPTION
**Pull request by bpneal**
~~When using react-virtualized use the CellMeasurer~~ see below

### CODE REVIEW

**Comment by bpneal** [comment]
Added optional prop `isDynamicHeight` which is be default false.

```
<SortableTree 
    ....
    isDynamicHeight={true}
/>
```

When true, each cell / row will be rendered using the `react-virtualized` `CellMeasurer`.

**Comment by bpneal** [comment]
You can also force a resize, in a parent Component

```
class MyComponent extends Component {

    forceResize = () => {
        setTimeout(() => {
            this._sortableTree.handleResize();
        }, 0);
    }

    render() {
        ...

        return (
            <SortableTree
                ...
                isDynamicHeight={true}
                ref={(ref) => {
                    this._sortableTree = ref;
                }}
            />
        );
    }
}
````

**Comment by bpneal** [comment]
Rebased Latest Master Changes

**Comment by fritz-c** [comment]
Thanks for keeping up with this and making it mergeable again. I've been going over the code and trying it out on the demo screen, and I've noticed a couple of issues:
1. `isOver` isn't getting set within the `DefaultNodeRenderer` for some reason, so the "landing pad" is always red.

2. Row heights are not adjusted in the middle of dragging actions, so the wrong heights are given to the rows until you drop the node.
    1. I tried to fix this by adding some cache-clearing statements to `dragHover`, but it doesn't work consistently, and puts significant load on the CPU to recalculate row heights.

I pushed the modifications I made so far to [bpneal-feature/useReactVirtualizedCellMeasurer](https://github.com/fritz-c/react-sortable-tree/compare/bpneal-feature/useReactVirtualizedCellMeasurer). However, I will need your help figuring out solutions to the issues above before we get this merged.

**Comment by bpneal** [comment]
@fritz-c thanks for the response.

1. The `isOver` is not set because `CellMeasurer` does not pass through props given in https://github.com/fritz-c/react-sortable-tree/blob/master/src/tree-node.js#L132

The `DynamicRow` (https://github.com/bpneal/react-sortable-tree/blob/feature/useReactVirtualizedCellMeasurer/src/react-sortable-tree.js#L46) was written to by pass this issue by forwarding the props, how ever I have created a pull request with `react-virtualize` to solve this problem https://github.com/bvaughn/react-virtualized/pull/628

2. Will have a play and see what I can do

**Comment by fritz-c** [comment]
@bpneal Ah, now the extra `DynamicRow` component class you had made makes sense. Sorry about deleting that. Let me know later if you make any progress on the height-while-dragging issue.

**Comment by bpneal** [comment]
Just need to fix the height-while-dragging issue

**Comment by antoniosemeraroF** [comment]
Hi! Any news about this feature?

**Comment by bpneal** [comment]
@antoniosemeraroF Sorry, I haven't had time to look into this further. It is still something that I want to implement, but will need to spend some more time getting it pull request ready

**Comment by topolanekmartin** [comment]
Hello, this feature would be really good.

Are there any progress in implementing this feature?

**Pull request closed without merging**
