### PR TITLE
Adding storybook link to codesandbox.io sandboxes for each story

### PR DESCRIPTION
**Pull request by wuweiweiwu**
#200 

Also updated the jest snapshot. 

This is what the source link and sandbox link look like now.
screen shot 2018-01-17 at 9 10 44 pm

### CODE REVIEW

**Comment by fritz-c** [comment]
Wooow... I was caught off-guard by this one. Thanks for taking the initiative and putting in the time to setup the sandboxes. 

I had been trying to figure out a way to generate the sandbox on-the-fly, based on our knowledge of the location of the files in the repo. I don't want to undermine your efforts so far, but my ideal solution would:
- fetch the source code file contents
- omit or rewrite `import` statements that would break inside codesandbox's environment
- submit the file contents via a form on the page to the [Codesandbox Define API](https://codesandbox.io/docs/importing#define-api)

I was stuck on this before because the Codesandbox Define API didn't exist at that time 😏 

If this sounds like too much work (I feel bad for critiquing anything after you've contributed so much), I will get around to it myself soon.

The appearance is great, btw. I want to preserve that.

**Comment by wuweiweiwu** [comment]
Oh oh that makes a lot of sense. I would love to work on it!

From my understanding. Would it be a build step where we upload the modified code to codesandbox.io and save the links in a config somewhere before you run `npm run deploy`?

**Comment by fritz-c** [comment]
Not a build step. On the page, when the dev clicks on the link, a loading indicator spins as we fetch the data from github (or rawgit, if github isn't cooperative), modifies the data as necessary, and then creates an invisible form to use to submit to the codesandbox API (similar to [their example](https://codesandbox.io/docs/importing/#example-sandbox-1)). The dev's page should transition to a fresh sandbox.

**Comment by wuweiweiwu** [comment]
Ohhh ok that makes sense. The example was very informative! I'll get on that

**Pull request closed without merging**
