### PR TITLE
Update react-sortable-tree.js

### PR DESCRIPTION
**Pull request by janumathy**
Added key enter prop to accomplish accessibility feature

### CODE REVIEW

**Comment by wuweiweiwu** [comment]
@janumathy can you clarify how this would accomplish the accessibility feature?

**Comment by fritz-c** [comment]
I couldn't find this attribute documented anywhere. What does it do?

**Comment by wuweiweiwu** [comment]
Not sure. I think he just added a new function prop

**Comment by janumathy** [comment]
Hi, 
I am still working on it. However giving you some context. I am using SortableTreeWithoutDndContext, I need to select node with enter key and drop the selected node in external drop area.  For this I am having handler in my code to set selected node in state. Drop area will read from state to show the selected node. 
This handler I am calling from my custom nodeContentRenderer so that I can pass  node object when onKeyPress event is triggered. This is the code snippet in my custom nodeContentRender
        // Show the handle used to initiate a drag-and-drop            handle = connectDragSource(                <div className={                    `row ${isLandingPadActive ? `rowLandingPad` : ''}                            ${isLandingPadActive && !canDrop ? `rowCancelPad` : ''}                            ${isSearchMatch ? `rowSearchMatch` : ''}                            ${isSearchFocus ? `rowSearchFocus` : ''}                            ${className ? className : ''}`}>                    <div className={'moveHandle'}/>                    <div className={ `rowContents ${!canDrag ? `rowContentsDragDisabled` : ''}`}>                        <div className='rowLabel' tabIndex={0} onKeyPress={(e) => { (e.key === 'Enter' ? keyEnter({node, parentNode}) : null); }}>

keyEnter prop is what passed to SortableTreeWithoutDndContext from my function and being passed from SortableTreeWithoutDndContext to nodeContentRenderer again. 
However after reading the specifications I think I have to use generateNodeProps to pass this handler function. Will try it, if it works I hope I don’t need this prop in react-sortable-tree js. 
Please confirm my understanding.
Thanks,Janagi

On 06-Feb-2018, at 11:24 AM, Wei-Wei Wu <notifications@github.com> wrote:



Not sure. I think he just added a new function prop

**Comment by wuweiweiwu** [comment]
@janumathy I'm going to close this as it seems like it is no longer being worked on. Feel free to reopen!

**Pull request closed without merging**
