### PR TITLE
[WIP] Configuring flow for react-sortable-tree

### PR DESCRIPTION
**Pull request by wuweiweiwu**
#257 

- [x] configuring npm run scripts
- [x] set up flow-typed
- [x] `react-virtualized` doesn't have flow types .. write flow wrapper
- [ ] type util functions
- [ ] type components

### CODE REVIEW

**Comment by wuweiweiwu** [comment]
@fritz-c I think there is going to be significant code changes. Should I do them incrementally and merge when a portion is done (ie. a file, etc)?

**Comment by fritz-c** [comment]
Yes, incrementally would be good. Just give the word when you think it’s ready.

**Comment by wuweiweiwu** [comment]
@fritz-c I finished flow typing some minor files :)

I got rid of propTypes in favor of  flow for more specific typing and static analysis. Also preserved the runtime propTypes validation by using `flow-react-proptypes` babel plugin to convert our flow types to propTypes

**Comment by wuweiweiwu** [comment]
Going to close this. I think we should migrate to `getDerivedStateFromProps` first. Also fix some major issues

**Pull request closed without merging**
