### PR TITLE
Insert nodes

### PR DESCRIPTION
**Pull request by NourSammour**
add ability to add items to list

### CODE REVIEW

**Comment by NourSammour** [comment]
@fritz-c Thanks for your hard work,
I added ability to add items to tree
Let me know if you are interested in merging it

**Comment by fritz-c** [comment]
I like this code. I didn't realize it just took a couple modifications to the react-sortable-tree.js source to allow for dragging around the outside. In order to provide this for a more general audience, here are the issues I think need taking care of:

1. If you drag a `Node` in from the outside, you cannot cancel the operation by moving the pointer back out. Canceling in this way leaves the tree unstable and un-draggable.
2. The original drag-and-drop code uses `monitor.getDifferenceFromInitialOffset().x` to determine the level to drop the node inside the tree. This doesn't work well when the element you're dragging doesn't line up perfectly at the same clientX as the left side of the tree. hover-shifted
Here you can see I'm quite far to the right with this element, but it's still assuming I want to place it in the leftmost level.
3. This is more of a consideration for developers - the amount of extra code necessary to implement an outside drag source (as in your `node.js` file) could probably be reduced. Something like an exported helper function you can call on your own components might be nice.

**Comment by fritz-c** [comment]
@cpunion I just noticed the scale of your contributions (#64). Thank you for that. If you can offer any solutions to the problems above I'd appreciate it.

**Comment by cpunion** [comment]
Good job @NourSammour! Steps forward :-)

And base on @fritz-c 's list, maybe should add:

4. Change the preview when dragging in/out of the tree. So if necessary, we need a DragLayer and let it render different nodes by dragging item type.

**Comment by NourSammour** [comment]
i'll work on it, thanks for your feedback 👍

**Comment by NourSammour** [comment]
@fritz-c I solved your comments
for point#1 it's not perfect solution, i added update field to each treeData item.. so i can force tree to reload... any help to find better solution?

**Comment by NourSammour** [comment]
> Change the preview when dragging in/out of the tree. So if necessary, we need a DragLayer and let it render different nodes by dragging item type.
your comments is unclear, can you give me more details or help me in implement it

**Comment by smtx** [comment]
+1

**Comment by chalda** [comment]
really looking for this functionality in my project, already spent some time trying to build it on top of react-sortable-tree. any way to merge this in to have it work natively in the package?

**Comment by fritz-c** [comment]
This functionality is now available in v0.1.20. PR #113, which was based on work here, is what ended up being merged in.

**Pull request closed without merging**
