### PR TITLE
Fix loadLazyChildren with children as function

### PR DESCRIPTION
**Pull request by jarandrew**
Related in #211

### CODE REVIEW

**Comment by megaboich** [comment]
Hi @jarandrew,

I do like your pull request, it seems to be fixing problem which I also encounter with lazy loading tree. Why did you close it?

**Comment by jarandrew** [comment]
Hi @megaboich

Because I was updating Drag & Drop modules from your dndManager, I also needed to commit others in this PR that might be not related lazy loading.
If you want to update lazy loading only, you can pickup changes from above commit,  https://github.com/fritz-c/react-sortable-tree/pull/214/commits/718addef446b8f27baccaa2d3e2272bb03c46709

**Comment by S-Eddine** [comment]
any news about lazy loading plz? @jarandrew  @megaboich 
thanks

**Comment by megaboich** [comment]
Unfortunately I don't have any good new from my side. 
My priorities have changed, and I am not working on it anymore and I doubt that I will continue on it.

Currently I know of two issues which are still not fixed:
https://github.com/frontend-collective/react-sortable-tree/issues/369
https://github.com/frontend-collective/react-sortable-tree/issues/298

**Comment by S-Eddine** [comment]
@megaboich okay, :/

**Pull request closed without merging**
